### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by SimonSK** [teamnsrg/go-ethereum#15]
- [x] #13 make a generic sql statement closing function
- [ ] #13 stmt.Exec()'s expected argument is ambiguous. consider ORM.
- [x] #16 move all sql related functions to a separate file
- [x] #16 make re-dial frequency as an configurable option
- [x] #16 update daofork check
- [x] remove case-study logging (Proto messages) from node-finder
- [x] #24 split the too_many_peers_counter field into 2
- [x] #24 add counters for hello and status in node_info table
- [ ] #28 look into dyndials made to nodes randomly chosen from node table
- [ ] #27 add manspreading proxy to node-finder
- [ ] #26 look into how a different size for `dynPeers` affects node discovery frequency
- [ ] find out what slows down discoverTask
- [x] add `logtofile` option to node-finder. see eth-monitor's in #35
- [x] implement JS calls similar to those in #35 for node-finder
- [x] fix node-finder (re)dial logic. see eth-monitor's in #33 
- [ ] find out if eth-monitor should broadcast blocks
- [x] addBlacklist should apply to udp discovery as well (both node-finder and eth-monitor)
- [x] [node-finder] fix the file-descriptor blocking issue with `tcpinfo` package. see `eth-monitor` fix at #54.
- [ ] [node-finder] resolve incoming addresses
- [x] [node-finder] change sql configuration so that ibdata1 doesn't grow infinitely
- [x] [node-finder] simplify operations related sqldb
